site_name: BDK React Native
site_description: React Native language bindings for the Bitcoin Development Kit.
site_url: https://bitcoindevkit.github.io/bdk-rn/
repo_url: https://github.com/bitcoindevkit/bdk-rn
repo_name: bitcoindevkit/bdk-rn

theme:
  name: material
  icon:
    logo: material/react
  palette:
    primary: orange
    accent: deep orange
  features:
    # - navigation.tabs
    # - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Overview: index.md
  - Example Apps: example-apps.md
  - Development: development.md
  - Testing: testing.md
  - Notes: notes.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - toc:
      permalink: true
